spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://yoh-db:5433/yoh
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    show-sql: 'true'
    hibernate:
      ddl-auto: update
