version: '3'

services:
  yoh-backend:
    container_name: yoh-backend
    image: yoh-backend
    build:
      context: ./yoh-backend
      dockerfile: Dockerfile
    depends_on:
      - yoh-db
    links:
      - yoh-db
    ports:
      - 5000:8080
    env_file: &envfile
      - .env

  yoh-db:
    image: 'postgres:12.10'
    container_name: yoh-db
    env_file: *envfile
    ports:
      - 5432:5432
      
  flask:
    build: ./yoh-wrapper
    container_name: yoh-wrapper
    env_file: *envfile
    environment:
      - PYTHONUNBUFFERED=True                   
    restart: on-failure
    volumes:
      - type: bind
        source: ${GAMES_FOLDER}
        target: /wrapper/games
    depends_on:
      - yoh-backend
    ports:
      - "5050:5050"
    command: gunicorn main:"create_flask_app()" -b 0.0.0.0:5050 --reload --log-level debug --workers=4